version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: wemovies_php
    restart: on-failure
    volumes:
      - ./:/var/www/html
    platform: linux/arm64

  nginx:
    image: nginx:alpine
    container_name: wemovies_nginx
    restart: on-failure
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:20-alpine
    container_name: wemovies_node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    platform: linux/arm64
    tty: true
    command: sh -c "tail -f /dev/null"