parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Model/'
            - '../src/Kernel.php'

    # API Controllers
    App\Application\Api\:
        resource: '../src/Application/Api/'
        tags: ['controller.service_arguments']

    # Web Controllers
    App\Application\Web\:
        resource: '../src/Application/Web/'
        tags: ['controller.service_arguments']

    # TMDB Client concret
    app.tmdb.client:
        class: App\Infrastructure\TMDB\Client\TMDBClient
        arguments:
            $apiKey: '%env(TMDB_API_KEY)%'

    # Bind interface to implementation
    App\Infrastructure\TMDB\Client\TMDBClientInterface: '@app.tmdb.client'

when@test:
    services:
        app.tmdb.client:
            class: App\Infrastructure\TMDB\Client\StubTMDBClient
            public: true